#!/usr/bin/env python3
"""Split the generated dashboard data into ONE cacheable bundle per season.

    py laliga_dashboard/build_split.py

Reads the monolithic builder outputs (data.js, players.js, shots.js) and writes:

    data/index.js         window.LL_INDEX  = {generated, v, defaultSeason, seasons:{key:{status,label,...}},
                                              teamColors:{team:[primary, secondary]}}
    data/<season>.js      window.LL_DATA.seasons[<season>] / LL_PLAYERS[<season>] / LL_SHOTS[<season>]

The site loads data/index.js statically and then fetches only the season being viewed
(app.js `loadSeason`), so the first paint downloads ~1.7 MB instead of the full 8+ MB
of every season, and a completed season's bundle never changes again (long cache).
`v` is a content hash of the bundles, used as the ?v= cache-buster for the per-season
files and the per-match detail files. Run this after build_data / build_players /
build_shots (build_site.py does).
"""
import hashlib
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT_DIR = os.path.join(HERE, "data")
sys.path.insert(0, ROOT)


def _read_js(path):
    """Return the JSON object assigned in a `window.X = {...}` builder file."""
    if not os.path.exists(path):
        return {}
    txt = open(path, encoding="utf-8").read()
    m = re.search(r"=\s*(\{.*\})\s*;?\s*$", txt, re.S)
    return json.loads(m.group(1)) if m else {}


def _team_colors():
    try:
        from laliga.team_colors import LALIGA_TEAM_COLORS
    except Exception:
        return {}
    return {t: [c.get("primary", ""), c.get("secondary", "")] for t, c in LALIGA_TEAM_COLORS.items()}


def _dump(obj):
    return json.dumps(obj, ensure_ascii=False, separators=(",", ":"))


def main():
    data = _read_js(os.path.join(HERE, "data.js"))
    players = _read_js(os.path.join(HERE, "players.js"))
    shots = _read_js(os.path.join(HERE, "shots.js"))
    seasons = data.get("seasons", {})
    if not seasons:
        print("build_split: data.js has no seasons; nothing to do")
        return
    os.makedirs(OUT_DIR, exist_ok=True)

    digest = hashlib.sha1()
    written = []
    for key in sorted(seasons):
        bundle = (
            "// AUTO-GENERATED by build_split.py — one season per file; do not edit by hand.\n"
            "window.LL_DATA=window.LL_DATA||{seasons:{}};"
            "window.LL_PLAYERS=window.LL_PLAYERS||{};"
            "window.LL_SHOTS=window.LL_SHOTS||{};\n"
            "window.LL_DATA.seasons[" + _dump(key) + "]=" + _dump(seasons[key]) + ";\n"
            "window.LL_PLAYERS[" + _dump(key) + "]=" + _dump(players.get(key, [])) + ";\n"
            "window.LL_SHOTS[" + _dump(key) + "]=" + _dump(shots.get(key, [])) + ";\n"
        )
        path = os.path.join(OUT_DIR, key + ".js")
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(bundle)
        digest.update(bundle.encode("utf-8"))
        written.append((key, os.path.getsize(path)))

    index = {
        "generated": data.get("generated", ""),
        "v": digest.hexdigest()[:10],
        "defaultSeason": data.get("defaultSeason") or sorted(seasons)[-1],
        "seasons": {
            k: {
                "status": s.get("status", ""),
                "counts": s.get("counts", {}),
            } for k, s in seasons.items()
        },
        "teamColors": _team_colors(),
    }
    with open(os.path.join(OUT_DIR, "index.js"), "w", encoding="utf-8") as fh:
        fh.write("// AUTO-GENERATED by build_split.py — season list + cache version; do not edit by hand.\n")
        fh.write("window.LL_INDEX=" + _dump(index) + ";\n")

    # Drop bundles for seasons that no longer exist.
    keep = {k + ".js" for k in seasons} | {"index.js"}
    for f in os.listdir(OUT_DIR):
        if f.endswith(".js") and f not in keep:
            os.remove(os.path.join(OUT_DIR, f))

    for key, size in written:
        print(f"  data/{key}.js  {size / 1024:.0f} KB")
    print(f"build_split: {len(written)} season bundles, v={index['v']}")


if __name__ == "__main__":
    main()
