// AUTO-GENERATED by build_data.py — do not edit by hand.
window.LL_DATA = {
 "generated": "2026-07-04 02:00",
 "defaultSeason": "2025-26",
 "seasons": {
  "2025-26": {
   "season": "2025-26",
   "status": "not_started",
   "counts": {},
   "standings": [],
   "matches": [],
   "xgRecords": [],
   "crests": {},
   "teams": []
  },
  "2026-27": {
   "season": "2026-27",
   "status": "not_started",
   "counts": {},
   "standings": [],
   "matches": [],
   "xgRecords": [],
   "crests": {},
   "teams": []
  }
 }
};
